/**
 * `bahrawy-calendar init` — scaffold all calendar UI components.
 */

import { resolve, dirname } from 'path';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'fs';
import chalk from 'chalk';
import {
  REGISTRY,
  resolveAllDependencies,
  getRequiredPackages,
  getRequiredShadcn,
} from './registry.js';

interface InitOptions {
  dest: string;
  overwrite: boolean;
}

export async function init(options: InitOptions) {
  const destDir = resolve(process.cwd(), options.dest);

  console.log('');
  console.log(chalk.bold('  Bahrawy Calendar'));
  console.log(chalk.dim('  Scaffolding calendar components...'));
  console.log('');

  // Resolve all components and their dependencies
  const allComponents = resolveAllDependencies(Object.keys(REGISTRY));
  const allPackages = getRequiredPackages(allComponents);
  const allShadcn = getRequiredShadcn(allComponents);

  // Create destination directory
  if (!existsSync(destDir)) {
    mkdirSync(destDir, { recursive: true });
    console.log(chalk.green('  Created'), chalk.dim(options.dest));
  }

  // Copy component files
  let copiedCount = 0;
  let skippedCount = 0;

  for (const compName of allComponents) {
    const entry = REGISTRY[compName];
    if (!entry) continue;

    for (const file of entry.files) {
      const destPath = resolve(destDir, file);
      const destFileDir = dirname(destPath);

      if (!existsSync(destFileDir)) {
        mkdirSync(destFileDir, { recursive: true });
      }

      if (existsSync(destPath) && !options.overwrite) {
        skippedCount++;
        console.log(chalk.yellow('  Skipped'), chalk.dim(file), chalk.dim('(already exists)'));
        continue;
      }

      // Write a placeholder with instructions
      const content = generatePlaceholder(compName, file);
      writeFileSync(destPath, content, 'utf-8');
      copiedCount++;
      console.log(chalk.green('  Created'), file);
    }
  }

  console.log('');
  console.log(chalk.bold('  Summary'));
  console.log(`  ${chalk.green(String(copiedCount))} files created, ${chalk.yellow(String(skippedCount))} skipped`);
  console.log('');

  // Print required packages
  if (allPackages.length > 0) {
    console.log(chalk.bold('  Install required packages:'));
    console.log(`  ${chalk.cyan(`npm install ${allPackages.join(' ')}`)}`);
    console.log('');
  }

  // Print required shadcn components
  if (allShadcn.length > 0) {
    console.log(chalk.bold('  Install required shadcn/ui components:'));
    console.log(`  ${chalk.cyan(`npx shadcn@latest add ${allShadcn.join(' ')}`)}`);
    console.log('');
  }

  // Print usage
  console.log(chalk.bold('  Usage:'));
  console.log(chalk.dim('  import { BahrawyCalendar } from \'./components/bahrawy-calendar/BahrawyCalendar\';'));
  console.log(chalk.dim(''));
  console.log(chalk.dim('  <BahrawyCalendar />'));
  console.log('');
  console.log(chalk.bold('  Next steps:'));
  console.log(chalk.dim('  1. Copy the actual view components from the Bahrawy Calendar repo'));
  console.log(chalk.dim('     into the generated directory and update imports'));
  console.log(chalk.dim('  2. Or use the source components directly from src/components/'));
  console.log('');
}

function generatePlaceholder(compName: string, file: string): string {
  const entry = REGISTRY[compName];
  return `/**
 * ${entry?.description ?? compName}
 *
 * This is a placeholder generated by bahrawy-calendar-cli.
 * Replace this with the actual component from the Bahrawy Calendar source.
 *
 * Source: https://github.com/bahrawyX/bahrawys-calender/blob/main/src/components/${file}
 *
 * Required packages: ${entry?.packages.join(', ') || 'none'}
 * Required shadcn/ui: ${entry?.shadcnDeps.join(', ') || 'none'}
 */

// TODO: Copy the component source from the repository
// and update import paths to use bahrawy-calendar for core logic.
export {};
`;
}
